### PR TITLE
Add ReadMe

### PR DESCRIPTION
**Pull request by VictorAlagwu**

### CODE REVIEW

**Comment by ashwini0529** [comment]
Hey @VictorAlagwu, thank you for contributing. I would suggest you to go through the project and write a detailed README.

Maybe you can take this as a template: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by VictorAlagwu** [comment]
Ok will do that

**Comment by ashwini0529** [comment]
Hey @VictorAlagwu any updates? 😄

**Comment by VictorAlagwu** [comment]
No update, I try going through the project file to understand it,but I
have no idea how docker works,so I left it

On 10/5/17, Ashwini Purohit <notifications@github.com> wrote:
> Hey @VictorAlagwu any updates? 😄
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/GDGVIT/autodock/pull/7#issuecomment-334470957


-- 
Victor Alagwu
+234(817)-044-9567
www.victoralagwu.me
www.github.com/VictorAlagwu
www.linkedin.com/in/victor-alagwu-08416b94/

**Pull request closed without merging**
